title: Cybersecurity Portfolio
theme: minima

# IMPORTANT: ton site est servi sur /Cyber-Portfolio/
baseurl: "/Cyber-Portfolio"
url: "https://deferdam.github.io"

# Empêche minima de lister 300 pages dans le header
header_pages:
  - index.md

minima:
  skin: dark

markdown: kramdown
